황재영/먹을 것인가 먹힐 것인가.md
황재영/입국심사.md

#37 
먹을 것인가 먹힐 것인가 - 10분
입국심사 - 20분
이분탐색
1. 전형적인 이분탐색이다.
2. 반복문을 순회하며 먹는 쪽에서 먹힐 쪽에서의 인덱스를 탐색한다.
3. 가장 알맞는 인덱스를 이분탐색으로 해결한다.
1. 전형적인 파라메트릭 서치 문제이다.
2. 스케줄링 기반으로 시간을 증분하며 문제를 해결하는 게 아니라 시간을 기준으로 수용이 가능한지 불가능한지만 탐색한다.
3. 결과를 반환한다.

[황재영] 먹을 것인가 먹힐 것인가 / 입국심사

---

최우석/먹을 것인가 먹힐 것인가.md
최우석/입국심사.md

[최우석] 입국심사, 먹을 것인가 먹힐 것인가

---

장영지/먹을 것인가 먹힐 것인가.md

#38 
[먹을 것인가 먹힐 것인가](https://www.acmicpc.net/problem/7795)
한시간....

[영지] 먹을 것인가 먹힐 것인가.md

---

장영지/예상 대진표.md
장영지/행렬 테두리 회전하기.md

#41 
행렬 테두리 회전하기
예상 대진표
행렬 테두리 회전하기 50분
예상 대진표 30분
냅다 구현....
어떤 알고리즘을 사용하면 좋을지 잘 떠오르지가 않습니다ㅠㅠ 그래도 범위가 작아 구현으로 풀수있을것 같아 그냥 구현으로 풀었습니다.
코틀린에서 2차 배열 출력하는법 println(Arrays.deepToString(graph))

[영지] 행렬 테두리 회전하기, 예상 대진표

---

최우석/예상 대진표.md
최우석/행렬 테두리 회전하기.md

#41 
- 행렬 테두리 회전하기: 2시간
- 예상 대진표: 1시간
2개의 문제 다 제귀 함수를 활용하여 문제를 풀었습니다. 행렬 테두리는 순회하는 row, column 인덱스와 회전하는 각 꼭짓점의 값들간의 관계를 통해 순회하는 로직을 구현하는 것이 핵심이였습니다. 예상 대진표의 경우 2의 진수를 기준으로 이분 탐색 으로 풀이하였습니다.
- 재귀
- 이분 탐색
- Kotlin API
- Array 함수 다루기
- math: log2, pow
- for문: until, downTo
- 재귀를 다루는 방법
Kotlin 언어가 아직 서투른 것 같다. 꾸준하게 풀이를 해가는게 중요한 것 같다.

[최우석] 행렬 테두리 회전하기, 예상 대진표

---

황재영/예상대진표.md
황재영/행렬 테두리 회전하기.md

#41 
- 20분
- 1시간
둘 다 구현문제였다.
1. 예상대진표 
- 결국 모든 것들이 1:1로 이루어진 이진트리의 구조이다.
- 따라서 계속해서 모든 것들이 1 / 2로 비교될 수 있도록 현재의 번호를 계속해서 2로 나눠주었다. (나눈다는 것은 계속해서 중간결과를 단순화하기 위함이다)
- 양쪽이 1 / 2로 되었을 때 결과를 반환하면 된다.
2. 행렬 테두리 회전하기
- 그냥 단순 구현문제다.
- 행렬 테두리만 회전시키는 알고리즘을 별도로 구현한다.
- 쿼리를 반복하면서 최소인 경우만 구하면 끝이다.

[황재영] 행렬 테두리 회전하기, 예상대진표

---

황재영/롤케이크 자르기.md
황재영/쿼드 압축 후 개수 세기.md

#45 
- 롤케이크 자르기 - 5분
- 쿼드압축 후 개수 세기 - 1시간
- 롤케이크 자르기 - 그리디
- 쿼드압축 후 개수 세기 - 재귀
코틀린의 디버깅이 힘들다...

[재영] 롤케이크 자르기 / 쿼드 압축 후 개수 세기

---

최우석/롤케이크 자르기.md
최우석/쿼드압축 후 개수 세기.md

#45
- 롤케이크 자르기: 30분
- 쿼드압축 후 개수 세기: 30분
- 롤케이크 자르기: 왼쪽과 오른쪽의 모든 경우의 수를 구한 후 경우에 따라 개수가 같은지 비교하여 풀이했습니다.
- 쿼드압축 후 개수 세기: 재귀를 통해 풀이했습니다.
- 재귀
- 구현
- 생각보다 시간 복잡도를 너무 고려해서 풀이하지 않고 생각나는대로 풀었더니 됐다. 너무 어렵다고 생각이 들면 일단 구현해보고 시간이 초과될 경우 개선하는 방향으로 풀이도 해보자!
- 재귀가 생각보다 단순하게 구현될 수 있다는 것을 점점 알게 되는 것 같다. 갓재영!
-현재 풀이한 내용에서 좀 더 개선할 수 있는 부분이 있다고 느껴지는데 이는 스터디 시간에 피드백을 받아봐야겠다..

[우석] 롤케이크 자르기, 쿼드압축 후 개수 세기 풀이

---

장영지/롤케이크 자르기.md
장영지/쿼드압축 후 개수 세기.md

#46 
롤케이크 자르기 1시간
쿼드압축 후 개수 세기 1시간
쿼드압축은 어떻게 풀어야할까 고민을 많이하다 분할정복이라는 힌트를 봐버렸습니다.. 분할정복이라는 것을 알고 푸니 금방 풀렸음
map
분할정복

[영지] 롤케이크 자르기, 쿼드압축 후 개수 세기

---

장영지/2개 이하로 다른 비트.md
장영지/멀리 뛰기.md

#52 
2개 이하로 다른 비트 : 30분
멀리 뛰기 : 20분
2개 이하로 다른 비트 : 그리디
멀리 뛰기 : dp
Long type 최대값 넘어가는 부분을 생각을 못해 조금 헤맸습니다

[영지] 2개 이하로 다른 비트, 멀리 뛰기

---

강민혜/N으로 표현.md
강민혜/가장 많이 받은 선물.md

#56 
[가장 많이 받은 선물](https://school.programmers.co.kr/learn/courses/30/lessons/258712)
[N으로 표현](https://school.programmers.co.kr/learn/courses/30/lessons/42895)
가장 많이 받은 선물: 1시간
N으로 표현: 1시간 30분 (못품)
가장 많이 받은 선물: 구현(객체 활용)
N으로 표현: DP

[민혜] 가장 많이 받은 선물, N으로 표현

---

최우석/N으로 표현.md
최우석/가장 많이 받은 선물.md

#56
- [가장 많이 받은 선물](https://school.programmers.co.kr/learn/courses/30/lessons/258712) - 30분
- [N으로 표현](https://school.programmers.co.kr/learn/courses/30/lessons/42895) - 1시간 30분

[우석] 가장 많이 받은 선물, N으로 표현

---

장영지/마법의 엘리베이터.md
장영지/불량 사용자.md

#49 
불량 사용자, 마법의 엘리베이터
불량 사용자 1시간 -> 테스트 케이스 발견하는데 오래걸렸습니다ㅠ 질문하기 힌트 살짝봄
마법의 엘리베이터 1시간 -> 중복을 제거하는 방법을 찾지 못해서 실패~
불량 사용자 -> 완탐? 몰르겠어요
마법의 엘리베이터 -> 정수론

[영지] 불량 사용자, 마법의 엘리베이터

---

장영지/도넛과 막대 그래프.md
장영지/연속된 부분 수열의 합.md

#60 
연속된 부분 수열의 합, 도넛과 막대 그래프
연속된 부분 수열의 합(30분), 도넛과 막대 그래프(1시간30분)
연속된 부분 수열의 합(배열?), 도넛과 막대 그래프(구현, 그래프)
시작 정점을 찾는데서 좀 헤맸습니다~

[영지] 연속된 부분 수열의 합, 도넛과 막대 그래프

---

최우석/도넛과 막대 그래프.md
최우석/연속 부분 수열의 합의 개수.md

[우석] 연속된 부분 수열의 합, 도넛과 막대 그래프

---

장영지/두 원 사이의 정수.md
장영지/요격 시스템.md

요격 시스템, 두 원 사이의 정수
요격 시스템 30
두 원 사이의 정수 40
요격 시스템 : 그리디
두 원 사이의 정수 : 정수론 - 원의 방정식이 기억 안난서 검색해봤어요
또 Long 범위때매 조금 헤맸습니다. 변수 타입을 명시적으로 지정해주지 않으니 이런 문제가 있네요!

[영지] 요격 시스템, 두 원 사이의 정수

---

강민혜/두 원 사이의 정수 쌍.md

#64 
두 원 사이의 정수 쌍: 1시간..
피타고라스의 정리 식을 사용해서 바깥 원, 안쪽 원 두번 계산해서 구했어요!
수학..?
처음엔 입력값을 정수만 올 수 있다고 생각해서 시간을 버리고 잘못 푼 부분이 아쉬웠어요.
입력값에 무엇이 올 수 있는지 잘 생각해보고 해야겠어용

feat: 두 원 사이의 정수 쌍.md

---

황재영/N으로 표현.md
황재영/가장 많이 받은 선물.md

#56 
[프로그래머스 - 가장 많이 받은 선물](https://school.programmers.co.kr/learn/courses/30/lessons/258712?language=javascript)
[프로그래머스  - N으로 표현](https://school.programmers.co.kr/learn/courses/30/lessons/42895)
둘 다 30분

[재영] N으로 표현, 가장 많이 받은 선물

---

황재영/요격시스템.md

feat: 요격시스템.md

---

최우석/2개 이하로 다른 비트.md
최우석/마법의 엘리베이터.md
최우석/멀리 뛰기.md
최우석/불량 사용자.md

#49 #52
- 마법의 엘레베이터: 1시간 반
- 불량 사용자: 1시간 풀다 포기
- 2개 이하로 다른 비트: 1시간
- 멀리 뛰기: 20분
- 마법의 엘레베이터는 예외 케이스를 고려하면서 풀었습니다.
- 불량 사용자는 완전 탐색이라고 생각하고 구현하고 있습니다.
- 마법의 엘레베이터: 그리디?
- 불량 사용자: 완전 탐색

[우석] - 마법의 엘레베이터, 불량 사용자, 2개 이하로 다른 비트, 멀리 뛰기

---

강민혜/광물캐키.md

[민헤] 광물 캐키

---

황재영/광물 캐기.md
황재영/연속된 부분 수열의 합.md

#68 
[광물 캐기](https://school.programmers.co.kr/learn/courses/30/lessons/172927)
30분
그리디 / 정렬
* 1. 일단 5개씩 미네랄을 분리한다.
* 2. 5개에 대한 각각의 곡괭이별 피로도 합을 구한다.
* 3. 곡괭이의 수를 맞춘다. 이때 가장 피로도가 많이 드는 순으로 곡괭이들을 제거한다.
* 4. 5개씩 미네랄을 분리한 케이스들을 돌 / 철 / 다이아몬드 순으로 역으로 분리한다.
* 5. 돌 / 철 / 다이아몬드 순으로 곡괭이를 사용하면서 피로도를 계산한다.
* 6. 결과를 반환한다.

[재영] 광물 캐기

---

황재영/연속된 부분 수열의 합.md

#68 
연속된 부분 수열의 합
10분
1. 왼쪽 / 오른쪽 포인터를 달아서 그 안에 있는 합을 구한다.
2. 만약 
투 포인터를 활용하여 문제를 풀었어요.

[재영] 연속된 부분 수열의 합

---

장영지/호텔 대실.md
장영지/혼자 놀기의 달인.md

#82 
호텔 대실, 혼자 놀기의 달인
각각 30~40분
호텔... stack?
혼자 놀기 -> 그래프

[영지] 호텔 대실, 혼자 놀기의 달인

---

최우석/호텔 대실.md
최우석/혼자 놀기의 달인.md

#82
- 혼자 놀기의 달인: 20분
- 호텔 대실: 1시간
- 혼자 놀기의 달인: dfs
- 호텔 대실: 구현

[우석] 호텔 대실, 혼자 놀기의 달인

---

최우석/연속된 부분 수열의 합.md

[우석] - 연속된 부분 수열의 합 풀이

---

강민혜/시소 짝궁.md
강민혜/택배상자.md

[민혜] 시소 짝궁, 택배상자

---

강민혜/리코쳇 로봇.md
강민혜/숫자 카드 나누기.md

[민혜] 리코쳇 로봇, 숫자 카드 나누기

---

장영지/숫자 카드 나누기.md

[영지] 숫자 카드 나누기

---

황재영/리코쳇 로봇.md
황재영/숫자 카드 나누기.md
황재영/이모티콘 할인행사.md

#87 
- 이모티콘 할인행사 (프로그래머스)
- 리코쳇 로봇 (프로그래머스)
- 숫자카드 나누기 (프로그래머스)
- 이모티콘 할인행사 (프로그래머스) 30분
- 리코쳇 로봇 (프로그래머스) 20분
- 숫자카드 나누기 (프로그래머스) 20분
- 이모티콘 할인행사 (프로그래머스): 완전탐색
- 리코쳇 로봇 (프로그래머스): BFS
- 숫자카드 나누기 (프로그래머스): 그리디

[재영] 이모티콘 할인행사, 리코쳇 로봇, 숫자카드 나누기

---

장영지/시소 짝꿍.md
장영지/택배상자.md

#77 
택배 30분
시소 아직 못품ㅠㅠ
택배는 스택
시소는 수학같은데 아직 못풀었음

[영지] 택배 상자, 시소 짝꿍

---

최우석/리코쳇 로봇.md
최우석/숫자 카드 나누기.md

#87
- 숫자 카드 나누기: 30분
- 리코쳇 로봇: 1시간 30분

[우석] 숫자 카드 나누기, 리코쳇 로봇

---

장영지/n^2배열자르기.md
장영지/부대복귀.md
장영지/테이블 해시 함수.md

#91 #92 
n^2 배열자르기
테이블 해시 함수
부대복귀
n^2 배열자르기 20
테이블 해시 함수 20
부대복귀 30
bfs
좀 더 빨리 풀어애겠다.
코틀린 함수에 좀 익숙해진것 같다. 하지만 멀엇다

[영지] n^2 배열자르기, 테이블 해시 함수, 부대복귀

---

최우석/n^2 배열 자르기.md
최우석/부대복귀.md

#92 
- n^2 배열 자르기: 20분
- 부대복귀: 2시간(못품..)

[우석] n^2 배열자르기, 부대복귀

---

최우석/징검 다리 건너기.md
최우석/테이블 해시 함수.md

[우석] 징검 다리 건너기

---

장영지/네트워크.md
장영지/이중우선순위큐.md

#97 
네트워크, 이중 우선순위 큐
20, 30
그래프(bfs), 우선순위큐

[영지] 네크워트, 이중우선순위큐

---

장영지/가장 긴 팰린드롬.md

[영지] 가장 긴 팰린드롬
